export const ourTopDeals = [
  {
    isNew: true,
    imageURL: "https://www.adorama.com/images/product/3pactt.jpg",
    name: "Sony PlayStation 5 825GB Gaming Console w/God of War Ragnarok, Standard Edition",
    price: 16099.0,
    rating: 4.5,
    numReviews: 34,
    id: 1,
  },
  {
    isNew: false,
    name: "Nintendo Switch 64GB OLED Console with White Joy-Con Controllers and Bundle Kit",
    imageURL: "https://www.adorama.com/images/product/3pcfttaaaaa.jpg",
    price: 14099.0,
    rating: 3,
    numReviews: 34,
    id: 2,
  },
  {
    isNew: true,
    name: "Nintendo Switch 64GB OLED Console with White Joy-Con Controllers",
    imageURL: "https://www.adorama.com/images/product/3phb1.jpg",
    price: 8200.0,
    rating: 2,
    numReviews: 34,
    id: 3,
  },
  {
    isNew: false,
    name: "Microsoft Xbox Series S Gilded Hunters Bundle",
    imageURL: "https://www.adorama.com/images/product/3pp4aork3.jpg",
    price: 56000.0,
    rating: 2,
    numReviews: 34,
    id: 4,
  },
  {
    isNew: false,
    name: "Nintendo Switch 64GB OLED Console with Joy-Con Controllers and Bundle Kit",
    imageURL: "https://www.adorama.com/images/product/3pshpg.jpg",
    price: 34500.0,
    rating: 4,
    numReviews: 34,
    id: 5,
  },
  {
    isNew: false,
    name: "Nintendo Switch 64GB OLED Console with Neon Red & Neon Blue Joy-Con Controllers",
    imageURL: "https://www.adorama.com/images/product/niswioledrb.jpg",
    price: 20700.0,
    rating: 2,
    numReviews: 34,
    id: 6,
  },
  {
    isNew: false,
    name: "Microsoft Xbox Series S Console",
    imageURL: "https://www.adorama.com/images/product/3pvhq3.jpg",
    price: 18500.0,
    rating: 5,
    numReviews: 34,
    id: 7,
  },
];
